# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 828552c04a839c81dae684f0fc69755ed8aa84295f91db643880f5e8e125967d133f9f8e65646a695f3aaa818b2f3344200d158d36347bf60fd224db17479625

test:
  secret_key_base: d55296e23a12253bce979be3f2f10068a68a6e8fdc00da9f37912c8018f62fc0cd533c6aa2bc3348948cf62d58e1ffe0f6fea0771eab1571e4dadb3f63be5daf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
